name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install .[dev]
      - name: Ruff format
        run: ruff format .
      - name: Ruff check
        run: ruff check --output-format=github .
      - name: Pyright
        run: pyright .

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier:check
